name: create tag

on:
#  pull_request:
#    branches:
#      - main
#      - master
#    types:
#      - closed
  push:
    branches:
      - feat/#3_use_cobra

jobs:
  create-tag:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Build Code
        run: go build -o _artifact .

      - name: Show Version
        run: |
          VERSION=`./_artifact --version | awk '{print $3}'` \
          && echo $VERSION > TAG_NAME && echo $TAG_NAME

      - name: Create tag
        run: |
          git tag $(cat TAG_NAME) && \
          git push origin $(cat TAG_NAME)